// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8W9stI3eryYVTN2HU-AeAaeXCJeN0T1w',
    appId: '1:531550092197:web:1f3d87c51e5418d4e9c64c',
    messagingSenderId: '531550092197',
    projectId: 'bliss-cafe-system',
    authDomain: 'bliss-cafe-system.firebaseapp.com',
    storageBucket: 'bliss-cafe-system.firebasestorage.app',
    measurementId: 'G-NHYX17ET1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-avhXg5ECG9XBWKdiXDhC18xcl4Thlog',
    appId: '1:531550092197:android:7d831243ccd2c7f5e9c64c',
    messagingSenderId: '531550092197',
    projectId: 'bliss-cafe-system',
    storageBucket: 'bliss-cafe-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB92WNgnXutjdIq-jS5WTqqyZd-N_hy3mA',
    appId: '1:531550092197:ios:036353365c4530dde9c64c',
    messagingSenderId: '531550092197',
    projectId: 'bliss-cafe-system',
    storageBucket: 'bliss-cafe-system.firebasestorage.app',
    iosBundleId: 'com.example.farahBlissApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB92WNgnXutjdIq-jS5WTqqyZd-N_hy3mA',
    appId: '1:531550092197:ios:036353365c4530dde9c64c',
    messagingSenderId: '531550092197',
    projectId: 'bliss-cafe-system',
    storageBucket: 'bliss-cafe-system.firebasestorage.app',
    iosBundleId: 'com.example.farahBlissApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8W9stI3eryYVTN2HU-AeAaeXCJeN0T1w',
    appId: '1:531550092197:web:63375dfbfb04690fe9c64c',
    messagingSenderId: '531550092197',
    projectId: 'bliss-cafe-system',
    authDomain: 'bliss-cafe-system.firebaseapp.com',
    storageBucket: 'bliss-cafe-system.firebasestorage.app',
    measurementId: 'G-FERQQHTLF2',
  );

}